### ISSUE TITLE
Error building manual switch

### ISSUE THREAD

**Issue by rousseldenis** [GrandOrgue/ODFEdit#12]
`Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/denis/.local/pipx/venvs/odfedit/lib/python3.10/site-packages/src/OdfEdit.py", line 5526, in file_open
    if self.odf_conv.GO_ODF_build_from_HW_ODF(HW_ODF_file_name_str, GO_ODF_file_name, self.progress_status_update):
  File "/home/denis/.local/pipx/venvs/odfedit/lib/python3.10/site-packages/src/OdfEdit.py", line 3250, in GO_ODF_build_from_HW_ODF
    self.GO_ODF_build_Manual_object(HW_division_dic)
  File "/home/denis/.local/pipx/venvs/odfedit/lib/python3.10/site-packages/src/OdfEdit.py", line 3873, in GO_ODF_build_Manual_object
    self.GO_ODF_build_Manual_keyimage_by_switch(keys_switch_dic[midi_note_nb_int], keys_switch_dic[midi_note_nb_int + 1], GO_disp_manual_dic, GO_key_nb)
  File "/home/denis/.local/pipx/venvs/odfedit/lib/python3.10/site-packages/src/OdfEdit.py", line 4011, in GO_ODF_build_Manual_keyimage_by_switch
    HW_switch_dic['_GO_uid'] = GO_disp_manual_dic['_GO_uid']
KeyError: '_GO_uid'`

@eturpault This during building Rotterdam demo

**Comment by eturpault** [comment]
Thanks @rousseldenis for the report, I have fixed the issue for the next version, now OdfEdit can load this HW sample set without problem.
